# Generated by Django 5.2.11 on 2026-07-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year_of_publication', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_pages', models.IntegerField()),
            ],
        ),
    ]
